services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-jupyterlab
    working_dir: /code
    restart: always
    entrypoint: >
      jupyter-lab
        --allow-root
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --NotebookApp.token=''
        --notebook-dir=/code
    ports:
      - "8888:8888"
    volumes:
      - ./code:/code
