version: "3.9"
services:
  jupyter:
    build:
      context: .
    image: enginearn/python-jupyterlab
    container_name: python-jupyterlab
    working_dir: /root/code
    restart: always
    entrypoint: >
      jupyter-lab
        --allow-root
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --NotebookApp.token=''
        --notebook-dir=/root/code
    ports:
      - "8888:8888"
    volumes:
      - .:/root/code

  postgres:
    image: "postgres:15-alpine"
